include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_declare_return_types: true
    no_logic_in_create_state: true
    use_key_in_widget_constructors: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    avoid_redundant_argument_values: true
    directives_ordering: true
    sort_child_properties_last: true

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    use_build_context_synchronously: warning
    invalid_use_of_visible_for_testing_member: warning
    todo: ignore

