// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFIaOwx6gvfxYsjUhAuGC-JkSlMvF5qsw',
    appId: '1:559164198600:android:52c0a38fdf441b964edffd',
    messagingSenderId: '559164198600',
    projectId: 'imanagement-7bd21',
    storageBucket: 'imanagement-7bd21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqM4meUr8fV8GYkLYDIGzWO3R_Kgqogkk',
    appId: '1:559164198600:ios:e1ad3fc7095bc8814edffd',
    messagingSenderId: '559164198600',
    projectId: 'imanagement-7bd21',
    storageBucket: 'imanagement-7bd21.firebasestorage.app',
    iosBundleId: 'com.example.appInvv1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNXz0lG9acxUr9WHU2kW2VREDImkt1j9M',
    appId: '1:559164198600:web:2d6220b83bfb78984edffd',
    messagingSenderId: '559164198600',
    projectId: 'imanagement-7bd21',
    authDomain: 'imanagement-7bd21.firebaseapp.com',
    storageBucket: 'imanagement-7bd21.firebasestorage.app',
    measurementId: 'G-QQ2HC4T77P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqM4meUr8fV8GYkLYDIGzWO3R_Kgqogkk',
    appId: '1:559164198600:ios:e1ad3fc7095bc8814edffd',
    messagingSenderId: '559164198600',
    projectId: 'imanagement-7bd21',
    storageBucket: 'imanagement-7bd21.firebasestorage.app',
    iosBundleId: 'com.example.appInvv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNXz0lG9acxUr9WHU2kW2VREDImkt1j9M',
    appId: '1:559164198600:web:c1905e43dbd625fb4edffd',
    messagingSenderId: '559164198600',
    projectId: 'imanagement-7bd21',
    authDomain: 'imanagement-7bd21.firebaseapp.com',
    storageBucket: 'imanagement-7bd21.firebasestorage.app',
    measurementId: 'G-MZKSBLWBL8',
  );

}