name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PAGES_PROJECT_NAME }}
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
